### ISSUE TITLE
AwesomeOpenSource

### ISSUE THREAD

**Issue by jeffreyjackson** [tayllan/awesome-algorithms#16]
We are creating a github org for all awesome open source repos. I am working with a few individuals who are also managing their own awesome repos, and I think to gain more traction we need to work together. What are your thoughts about collectively moving your awesome repos to https://github.com/AwesomeOpenSource

The idea is that visibility for these repos would be increased due to more traffic to the org. What are your thoughts? Let me know if there is anything you'd like to discuss!

**Comment by Leviathan1995** [comment]
i don't konw how to do

**Comment by Leviathan1995** [comment]
i don't konw how to do

**Comment by jeffreyjackson** [comment]
https://github.com/tayllan/awesome-algorithms/settings and transfer the repo to the AwesomeOpenSource organization, I will make whoever transfers the repo an admin on the organization.

**Comment by Leviathan1995** [comment]
i can't open this website

**Comment by bucaran** [comment]
@tayllan @Leviathan1995 Hi!

@jeffreyjackson is talking about transferring _this_ repository to the AwesomeOpenSource organization. You will of course keep control and ownership over the repository. The idea is to have a central hub for all the _awesome_ lists.

@Leviathan1995 You can't access https://github.com/tayllan/awesome-algorithms/settings because you are not the owner of this repository. Only @tayllan or an administrator user can transfer the repository.

It's something like this:

![rt](https://cloud.githubusercontent.com/assets/8317250/7027210/43b14730-dd89-11e4-8c30-165a58a0f9e1.png)

**Comment by jeffreyjackson** [comment]
thanks for leading the way on this @bucaran

**Comment by jeffreyjackson** [comment]
cc @dkhamsing

**Comment by bucaran** [comment]
This is a formidable cause @jeffreyjackson, I am just supporting you. 

Let's do our best.

**Comment by Leviathan1995** [comment]
i am only a student, but i want to take part in your project,and i don't know how to do ,thanks

**Comment by tayllan** [comment]
Thanks for the offer man, but I'm not really interested.
I don't really see the point in creating such organization. Said visibility is already achieved with (awesome-awesomeness)[https://github.com/bayandin/awesome-awesomeness] and similar ones (and you can't argue with its 11k+ stars). Besides, everyone that you contacted seemed to be reluctant to reply, as no one wants to lose control over an even mildly famous GitHub repository right ?! :)

**Comment by jeffreyjackson** [comment]
i understand your position on this.  you wouldnt lose control.  you would still be an admin.  also, awesome-awesomeness hasn't be updated in months.  If we worked together under an org we could ensure things are always up to date.
