### ISSUE TITLE
Add a `contributing.md`

### ISSUE THREAD

**Issue by arthurvr** [tayllan/awesome-algorithms#18]
With clear guidelines on when and how to contribute.

See https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines

**Comment by tayllan** [comment]
Thanks man, but I find that to be way too bureaucratic for a repository that barely receives a PR/month.

**Comment by arthurvr** [comment]
> Thanks man, but I find that to be way too bureaucratic for a repository that barely receives a PR/month.

You should look at it another way: people don't know how to contribute and don't know what contributions are welcome, and that's why they don't contribute.

**Comment by tayllan** [comment]
That's indeed a valid point of view I hadn't thought about. But still, the default [contributing.md](https://github.com/sindresorhus/awesome/blob/master/contributing.md) that you passed me doesn't seem to help with that either, since it's just a bunch of rules about what the contributor should do prior to the PR.
But if you have something in mind that may guide the soon-to-be contributor as to what could be an awesome contribution, I'd be really thankful.

**Comment by arthurvr** [comment]
> passed me doesn't seem to help with that either, since it's just a bunch of rules about what the contributor should do prior to the PR.

Clear guidelines help to get better contributions and vice-versa. If you don't know how to form your contribute, that doesn't really encourage contribution.

> But if you have something in mind that may guide the soon-to-be contributor as to what could be an awesome contribution, I'd be really thankful.

What things are welcome on the list? In other words: What things do we believe are awesome? Without knowing that you can't contribute...

**Comment by tayllan** [comment]
I see, got your point now. I'll think about it and add a guideline right after. Thanks.
